# ~/.config/helix/languages.toml

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "emmet-ls"]

[[language]]
name = "python"
language-servers = ["pylsp"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]

[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "emmet-ls"]

[[language]]
name = "typescript"
language-servers = ["typescript-language-server", "emmet-ls"]

[language-server.emmet-ls]
command = "emmet-ls"
args = ["--stdio"]

